version: '3.3'

volumes:
  db_value:
  static_value:
  media_value:
  frontend_value:

services:

  db:
    container_name: db
    image: postgres:13.0-alpine
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    container_name: foodgram_backend
    image: alexbareysha/foodgram_backend
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/

  frontend:
    container_name: foodgram_frontend
    image: alexbareysha/foodgram_frontend
    volumes:
      - frontend_value:/app/build/
    depends_on:
      - backend

  nginx:
    container_name: foodgram_gateway
    image: alexbareysha/foodgram_gateway
    ports:
      - 80:80
    env_file:
      - ./.env
    volumes:
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - frontend_value:/usr/share/nginx/html/
    depends_on:
      - frontend
      - backend
